package net.kasax.challengecraft.casino;

import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import it.unimi.dsi.fastutil.objects.Object2IntMap;
import net.kasax.challengecraft.ChallengeCraft;
import net.minecraft.core.Holder;
import net.minecraft.core.component.DataComponents;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.Identifier;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.enchantment.Enchantment;
import net.minecraft.world.item.enchantment.ItemEnchantments;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;

/**
 * The Jeton value of every item, taken over from ProjectE's EMC (MIT, sinkillerj/ProjectE).
 *
 * <p>The table itself is data, not code: {@code data/challengecraft/casino/emc_values.json} is
 * generated by {@code scripts/casino/emc_calc.py} from ProjectE's base values and the real 26.3
 * recipes (cheapest recipe wins, ores and raw materials are worthless — exactly ProjectE's rules).
 * Doing it offline keeps the mod clear of the recipe API, which changes shape every version.
 *
 * <p>On top of the base value this applies ProjectE's two stack processors: damaged tools lose
 * value in proportion to lost durability, and every enchantment adds {@code 5000 / weight × level}.
 */
public final class EmcValues {
    /** ProjectE's default {@code enchantment_emc_bonus}. */
    private static final long ENCHANT_BONUS = 5_000L;

    /** Valued, but never sold back by the cashier — nothing here may be conjured out of chips. */
    private static final Set<Item> NOT_FOR_SALE = Set.of(
            Items.DRAGON_EGG, Items.BEDROCK, Items.COMMAND_BLOCK, Items.BARRIER, Items.STRUCTURE_BLOCK,
            Items.SPAWNER, Items.TRIAL_SPAWNER, Items.VAULT, Items.HEAVY_CORE, Items.NETHER_STAR);

    private static Map<Item, Long> values = Collections.emptyMap();

    private EmcValues() {
    }

    public static void load() {
        Map<Item, Long> loaded = new HashMap<>();
        try (InputStream in = EmcValues.class.getResourceAsStream("/data/challengecraft/casino/emc_values.json")) {
            if (in == null) {
                ChallengeCraft.LOGGER.error("[Casino] emc_values.json is missing - every item will be worthless");
                values = Collections.emptyMap();
                return;
            }
            JsonObject root = JsonParser.parseReader(new InputStreamReader(in, StandardCharsets.UTF_8)).getAsJsonObject();
            JsonObject table = root.getAsJsonObject("values");
            for (Map.Entry<String, com.google.gson.JsonElement> e : table.entrySet()) {
                Item item = BuiltInRegistries.ITEM.getValue(Identifier.parse(e.getKey()));
                if (item == null || item == Items.AIR) continue;
                loaded.put(item, e.getValue().getAsLong());
            }
        } catch (Exception e) {
            ChallengeCraft.LOGGER.error("[Casino] could not read emc_values.json", e);
        }
        values = loaded;
        ChallengeCraft.LOGGER.info("[Casino] {} item values loaded", loaded.size());
    }

    /** Base value of one item in chips, 0 if it has none. */
    public static long baseValue(Item item) {
        Long v = values.get(item);
        return v == null ? 0L : v;
    }

    public static boolean hasValue(Item item) {
        return baseValue(item) > 0;
    }

    public static boolean isForSale(Item item) {
        return hasValue(item) && !NOT_FOR_SALE.contains(item);
    }

    /**
     * Whether an item carries other items (a filled shulker box, a bundle). Such stacks are never
     * bought or staked — their value would only be the empty container's and the contents would
     * be lost — so they count as worthless until emptied.
     */
    public static boolean hasContents(ItemStack stack) {
        var container = stack.get(DataComponents.CONTAINER);
        if (container != null && container.nonEmptyItemCopyStream().findAny().isPresent()) return true;
        var bundle = stack.get(DataComponents.BUNDLE_CONTENTS);
        return bundle != null && !bundle.isEmpty();
    }

    /** Value of ONE item of this stack in chips, with damage and enchantments applied. */
    public static long unitValue(ItemStack stack) {
        if (stack.isEmpty() || hasContents(stack)) return 0L;
        long value = baseValue(stack.getItem());
        if (value <= 0) return 0L;

        if (stack.isDamaged()) {
            int max = stack.getMaxDamage();
            int left = max - stack.getDamageValue();
            if (left <= 0 || max <= 0) return 0L;
            value = value * left / max;
        }

        ItemEnchantments enchantments = stack.getItem() == Items.ENCHANTED_BOOK
                ? stack.get(DataComponents.STORED_ENCHANTMENTS)
                : stack.get(DataComponents.ENCHANTMENTS);
        if (enchantments != null) {
            for (Object2IntMap.Entry<Holder<Enchantment>> entry : enchantments.entrySet()) {
                int weight = entry.getKey().value().definition().weight();
                if (weight > 0) {
                    value += ENCHANT_BONUS / weight * entry.getIntValue();
                }
            }
        }
        return value;
    }

    /** Value of the whole stack in chips. */
    public static long stackValue(ItemStack stack) {
        return unitValue(stack) * stack.getCount();
    }

    public static Map<Item, Long> all() {
        return values;
    }
}
