package net.kasax.challengecraft.challenges;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

public class TriviaQuestions {
    private static final List<TriviaQuestion> POOL = new ArrayList<>();
    private static final Random RANDOM = new Random();

    static {
        add("Which block cannot be pushed by a piston?", "Obsidian", "Stone", "Iron Block", "Diamond Block", 0);
        add("What is the maximum number of blocks a piston can push?", "8", "12", "15", "10", 1);
        add("What happens if you try to sleep in a bed in the Nether?", "You sleep normally", "The bed explodes", "Nothing happens", "The player catches fire", 1);
        add("Phantoms spawn when players haven’t slept for how many nights?", "One", "Two", "Three", "Five", 2);
        add("Who created Minecraft?", "Jeb", "Notch", "Dinnerbone", "C418", 1);
        add("Which biome is known for its tall spruce trees?", "Plains", "Forest", "Taiga", "Swamp", 2);
        add("What is the name of the boss that resides in the End dimension?", "Wither", "Ender Dragon", "Elder Guardian", "Warden", 1);
        add("What food restores the most hunger points?", "Steak", "Apple", "Bread", "Cooked Cod", 0);
        add("What is the most recently added food item in the game?", "Glow berries", "Sweet berries", "Honey bottle", "Dried Kelp", 0);
        add("What do Endermen drop when defeated?", "Ender Pearl", "Eye of Ender", "End Stone", "Chorus Fruit", 0);
        add("What item does Notch drop upon death?", "Golden Apple", "An Apple", "Diamond", "Nothing", 1);
        add("Which direction does a sunflower always face?", "North", "South", "East", "West", 2);
        add("What do you have to do in order to get the advancement Tactical Fishing?", "Catch a fish in a bucket", "Catch a fish with a rod", "Kill a fish with a sword", "Tame a cat with a fish", 0);
        add("What item will you always find in a Buried Treasure chest?", "Diamond", "Golden Apple", "Heart of the Sea", "Iron Ingot", 2);
        add("Which mob was created by a coding mistake?", "Creeper", "Zombie", "Spider", "Skeleton", 0);
        add("Does a Cave Spider drop special Cave Spider Eyes?", "Yes", "No", "Only on hard difficulty", "Only if killed by a player", 1);
        add("In which biome do Tropical Fish naturally spawn?", "Deep Ocean", "Warm Ocean", "Lukewarm Ocean", "Frozen Ocean", 2);
        add("What do you need to combine with diamonds to craft a diamond pickaxe?", "Iron Ingots", "Sticks", "Planks", "Gold Ingots", 1);
        add("How tall is a standard Minecraft player?", "1.5 blocks", "1.8 blocks", "2.0 blocks", "1.6 blocks", 1);
        add("What item is needed to make a banner pattern?", "Wool", "Paper", "Leather", "String", 1);
        add("What type of block do you need to create an enchantment table?", "Obsidian", "Crying Obsidian", "Bedrock", "Cobblestone", 0);
        add("How can players safely store their valuable items?", "In chests", "In fire", "Throw them on the ground", "In water", 0);
        add("What potion is made by brewing a Fermented Spider Eye in a Water Bottle?", "Potion of Strength", "Potion of Weakness", "Potion of Harming", "Potion of Slowness", 1);
        add("What happens when you feed Raw Cod to a Dolphin?", "It heals the player", "It leads to treasure", "It attacks the player", "Nothing", 1);
        add("What block is the taskbar icon of the Minecraft game?", "Dirt block", "Crafting table", "Grass block", "Diamond block", 1);
        add("Does a lightning strike turn a Rabbit into a Killer Rabbit?", "Yes", "No", "Only if it is raining", "Only in Java Edition", 1);
        add("What is the maximum size for a Nether portal?", "10x10", "23x23", "21x21", "Unlimited", 1);
        add("What food item is made by cooking raw pork?", "Cooked Beef", "Cooked Porkchop", "Cooked Mutton", "Bacon", 1);
        add("Which passengers can a Strider naturally spawn with?", "Zombie", "Baby Strider or Zombified Piglin", "Enderman", "Creeper", 1);
        add("How many mobs can be in a 'mob farm' area for spawning at a time?", "64", "128", "256", "Unlimited", 1);
        add("What is the highest number of blocks an unarmored player can fall without dying?", "20", "23", "25", "30", 1);
        add("How many Seecret updates were there?", "5", "10", "12", "15", 1);
        add("What entity is known for its ability to teleport?", "Creeper", "Enderman", "Ghast", "Phantom", 1);
        add("What is the only hostile mob that you can breed?", "Zombie", "Hoglin", "Creeper", "Blaze", 1);
        add("What biome is known for its large mushrooms and mycelium blocks?", "Dark Forest", "Mushroom Fields", "Swamp", "Jungle", 1);
        add("Which creatures in Minecraft drop gunpowder?", "Creeper and Ghast", "Zombie and Skeleton", "Spider and Witch", "Enderman and Shulker", 0);
        add("What item do you need to tame a wolf?", "Fish", "Bone", "Meat", "Seed", 1);
        add("What type of block do Slimes spawn in?", "Slime chunks", "Sand blocks", "Grass blocks", "Stone blocks", 0);
        add("What do bees produce?", "Sugar", "Honey", "Wax", "Milk", 1);
        add("How high can an egg be stacked?", "64", "16", "32", "1", 1);
        add("How long is a full day/night cycle in real time?", "10 minutes", "20 minutes", "30 minutes", "15 minutes", 1);
        add("What type of block can Sugar Cane not be placed on?", "Sand", "Gravel", "Dirt", "Grass", 1);
        add("Which creature drops feathers?", "Sheep", "Chickens", "Pigs", "Cows", 1);
        add("Aside from Plains, what biome can Donkeys spawn in?", "Forest", "Savanna", "Desert", "Taiga", 1);
        add("How many different songs can be played with a Goat Horn?", "5", "7", "10", "12", 1);
        add("What happens when lightning strikes a pig?", "It dies", "It turns into a Zombified Piglin", "It turns into a Hoglin", "Nothing", 1);
        add("Which mob is no longer tamable?", "Wolf", "Ocelot", "Cat", "Parrot", 1);
        add("What color is the 'mall' Music Disc?", "Green", "Purple", "Red", "Blue", 1);
        add("Which creature does the Fox not attack?", "Chicken", "Wolf", "Rabbit", "Fish", 1);
        add("Can you Place Water in the Nether?", "Yes", "No", "Only with a bucket", "Only in creative mode", 1);
        add("Which food item is harmful to Parrots?", "Apple", "Cookie", "Seeds", "Wheat", 1);
        add("What type of stone is created when water flows over lava?", "Stone", "Cobblestone", "Obsidian", "Basalt", 1);
        add("How do you create a Mule mob?", "Breeding two Horses", "Breeding a Horse and a Donkey", "Breeding two Donkeys", "Finding it in the wild", 1);
        add("Which mob can you tame with fish?", "Wolf", "Cat", "Horse", "Pig", 1);
        add("What is the rarest block in the game?", "Diamond Ore", "Dragon Egg", "Beacon", "Netherite Block", 1);
        add("Which underwater mob is not aquatic?", "Drowned", "Guardian", "Axolotl", "Cod", 0);
        add("How many blocks can silverfish infest?", "5", "7", "10", "12", 1);
        add("What material do you need to craft a map?", "Paper and String", "Paper and a Compass", "Paper and Leather", "Paper and Gold", 1);
        add("Which flower is only one block tall?", "Sunflowers", "Allium", "Lilac", "Rose Bush", 1);
        add("Where can you naturally find blue orchids?", "Forest", "Swamp", "Plains", "Desert", 1);
        add("What is the rarest ore in Minecraft?", "Diamond Ore", "Emerald Ore", "Gold Ore", "Iron Ore", 1);
        add("What sound cannot be played by adding an item or block with a Note Block?", "Piano", "Cymbal", "Bass", "Flute", 1);
        add("What item is used to breed Camels?", "Wheat", "Cactus", "Apple", "Carrot", 1);
        add("What is the default character skin for a new player in Minecraft?", "Alex", "Steve", "Zob", "None", 1);
        add("What item is required to enter The End?", "Eye of Ender", "Ender Pearl", "Nether Star", "Dragon Egg", 0);
        add("Which block can be used to create an infinite water source?", "Sand", "Water source blocks", "Sponge", "Cauldron", 1);
        add("Which blocks have a Creeper face?", "Chiseled Sandstone and Cyan Glazed Terracotta", "Stone Bricks", "Smooth Quartz", "Gilded Blackstone", 0);
        add("What is the only Tipped Arrow that can be obtained naturally – no crafting required?", "Arrow of Poison", "Arrow of Slowness", "Arrow of Strength", "Arrow of Harming", 1);
        add("What material do you need to build a crafting table?", "Cobblestone", "Wooden planks", "Iron Ingots", "Sticks", 1);
        add("What is the genre of the Minecraft movie?", "Horror", "Action-Adventure", "Comedy", "Documentary", 1);
        add("Where was A Minecraft Movie filmed?", "Canada", "New Zealand", "USA", "Australia", 1);
        add("What item do the characters combine to enter the Overworld?", "An Orb and a Crystal", "A Map and a Key", "A Sword and a Shield", "A Portal and a Core", 0);
        add("What unique tribute appears in the film?", "A statue of Steve", "A pig wearing a crown", "A gold block", "A custom cape", 1);
        add("Who composed the music for the movie?", "C418", "Daniel Pemberton", "Hans Zimmer", "Lena Raine", 1);
        add("A famous YouTuber is said to have a cameo in the film. Who is it?", "MrBeast", "DanTDM", "Dream", "PewDiePie", 1);
        add("What year was A Minecraft Movie released?", "2024", "2025", "2026", "2023", 1);
        add("Which actor was originally cast as Steve, but had to back out?", "Jack Black", "Matt Berry", "Jason Momoa", "Ryan Reynolds", 1);
        add("Who wins the fight, Steve or Chicken Jockey?", "Chicken Jockey", "Steve!", "It's a draw", "Neither", 1);
        add("What does an Ender Pearl do?", "Summons a mob", "Allows you to teleport", "Heals the player", "Creates a portal", 1);
        add("Who is the director of A Minecraft Movie?", "James Cameron", "Jared Hess", "Steven Spielberg", "Christopher Nolan", 1);
        add("What is Jason Momoa’s character, Garrett Garrison, nicknamed?", "The Builder", "The Garbage Man", "The Warrior", "The Miner", 1);
        add("The film features references to which other Jared Hess movie?", "Nacho Libre", "Napoleon Dynamite", "Gentlemen Broncos", "Masterminds", 1);
        add("What did Steve want to do as a child?", "Fly a plane", "Dig the mine", "Be a farmer", "Build a castle", 1);
        add("What is the name of the designer who references Mama Fratelli and the Skeksis?", "Malgosha", "Jeb", "Notch", "Alex", 0);
        add("What character does Jack Black play?", "Garrett", "Steve", "The King", "A Villager", 1);
        add("What real-world job did Steve have before becoming a blocky legend in the movie?", "Teacher", "Doorknob salesman", "Plumber", "Cook", 1);
        add("What is the main enemy faction in the movie?", "Zombies", "Piglins", "Endermen", "Creepers", 1);
        add("What’s the name of the world where the Piglins live?", "The Overworld", "The Nether", "The End", "The Void", 1);
        add("What happens when you mix hot lava and Chicken?", "It burns", "A Roasted Lava Chicken", "It explodes", "Nothing", 1);
        add("What material is used to build Steve’s third house?", "Wood", "Sheep’s wool", "Stone", "Dirt", 1);
        add("Who is the ruler of the Nether in the movie?", "The Wither", "Malgosha", "Herobrine", "Piglin King", 1);
        add("Who saved Henry’s team from the Zombies?", "Garrett", "Steve", "Alex", "Notch", 1);
        add("What mob explodes when it gets close to a player?", "Skeleton", "Creeper", "Zombie", "Enderman", 1);
        add("What was the first thing The Garbage Man crafted?", "A sword", "A bucket", "A pickaxe", "A torch", 1);
        add("How many Ender Pearls does Steve have?", "Many", "One", "None", "Five", 1);
        add("What does Steve use to tame the wolf named Dennis?", "Meat", "A femur bone", "Fish", "Seeds", 1);
        add("What item causes a temporary time loop in the film?", "A clock", "A bugged command block", "A portal", "A star", 1);
        add("What is the title of the song by Jack Black that entered the UK Top 40?", "Steve's Song", "“Steve’s Lava Chicken.”", "Mining Away", "Crafting Dreams", 1);
        add("Do Iron Golems attack all enemies?", "Yes", "No", "Only if hit", "Only Zombies", 1);
        add("What classic item is used to defeat the final boss in the movie?", "Diamond Sword", "A wooden shovel", "Bow and Arrow", "TNT", 1);
        add("What viral scene features a baby zombie riding a chicken?", "Chicken Jockey scene", "Spider Jockey scene", "Zombie Siege", "Village Raid", 0);
        add("What food item becomes a major plot point halfway through the movie?", "Golden Apple", "Suspicious stew", "Cake", "Bread", 1);
        add("How much armor does a full set of Netherite provide?", "8 points", "10 points", "20 points", "15 points", 1);
        add("Which Minecraft creature can swim and attack players underwater?", "Zombie", "Drowned", "Skeleton", "Creeper", 1);
        add("What is the name of the dimension that is accessed by building a portal with obsidian?", "The End", "The Nether", "The Aether", "The Void", 1);
        add("When was the very first version of Minecraft released?", "May 17, 2011", "May 17, 2009", "June 1, 2010", "November 18, 2011", 1);
        add("What is the maximum height of the Nether?", "256", "128", "320", "64", 1);
        add("What is not a villager profession?", "Librarian", "Engineer", "Farmer", "Cleric", 1);
        add("Which Cat variant exists as a texture file, but is never used in game?", "Siamese", "Gray Tabby", "Black", "Tuxedo", 1);
        add("How fast does lava flow in the Nether?", "1 block/s", "2 blocks per second", "5 blocks/s", "Instant", 1);
        add("In order to produce a vibraphone sound, what do you place under a Note Block?", "Block of Gold", "Block of Iron", "Stone", "Wood", 1);
        add("How do you duplicate Allays?", "Feed them cookies", "Give it an Amethyst Shard while it’s dancing", "Use a spawn egg", "They cannot be duplicated", 1);
        add("What color are Frogs spawned in the End?", "Orange", "Green", "White", "Purple", 1);
        add("What time of year are the spawning conditions for bats different than the rest?", "December", "October 20 – November 3", "July 4", "January 1", 1);
        add("Which mob has the highest total health in the game?", "Ender Dragon", "The Warden", "Wither", "Iron Golem", 1);
        add("What is the collective noun for a group of Endermen?", "A pack", "A haunting", "A swarm", "A group", 1);
        add("What mineral must be used to craft a beacon?", "A Diamond", "A Nether star", "A Dragon Egg", "A Netherite Ingot", 1);
        add("How many different types of Music Discs are there?", "10", "15", "20", "12", 1);
        add("Which block is completely unbreakable in Survival mode?", "Obsidian", "Bedrock", "Ancient Debris", "Iron Block", 1);
        add("What is the unused sound belonging to the Ghast?", "Friendly Purr", "Affectionate Scream", "Happy Meow", "Sad Cry", 1);
        add("What is the drop rate of Wither Skeleton Skulls?", "5%", "2.5%", "1%", "10%", 1);
        add("Which mineral can generate naturally in both the Overworld and the Nether?", "Diamond", "Gold", "Iron", "Coal", 1);
        add("What blocks can an Ender Dragon not destroy?", "Obsidian", "Iron Bars, End Stone, Obsidian, and Respawn Anchor", "Stone Bricks", "Diamond Blocks", 1);
        add("How many advancements are there in total?", "80", "102", "150", "50", 1);
        add("What is the original source of the Ghast sound?", "A baby", "C418’s cat", "A vacuum cleaner", "A wind chime", 1);
        add("Which mod developer helped with modeling the Horse?", "Mojang", "DrZhark", "Jeb", "Dinnerbone", 1);
        add("Right-clicking on what food item allows you to eat it faster?", "Dried Kelp", "Cake", "Steak", "Apple", 1);
        add("Which biome has the most passive mobs?", "Forest", "Plains", "Desert", "Mountains", 1);
        add("How many pieces of Netherite scrap would you need to build a fully powered beacon pyramid with all Netherite blocks?", "1000", "5904", "2000", "100", 1);
        add("How were the Enderman sounds made?", "Synthesizer", "Using a person’s distorted speech", "Animal noises", "Random clicks", 1);
        add("How many things can Diamonds be used to craft?", "10", "13", "15", "8", 1);
        add("Is Herobrine real?", "Yes", "No", "Only on Halloween", "In Bedrock Edition", 1);
        add("What was the game originally going to be called?", "Builder Game", "Cave Game", "Block World", "Mine & Craft", 1);
        add("What enchantment increases a player’s speed while wearing boots in water?", "Frost Walker", "Depth Strider", "Speed I", "Soul Speed", 1);
        add("Before its crafting recipe was removed, how did you craft an Enchanted Golden Apple?", "8 Gold Ingots", "An Apple and 8 blocks of Gold", "8 Diamonds", "8 Emeralds", 1);
        add("What is the main ingredient of a Turtle Master potion?", "Turtle Egg", "Turtle Shell", "Sea Grass", "Scute", 1);
        add("How many hearts does a standard player have?", "5", "10", "20", "15", 1);
        add("Which mob is scared of cats?", "Zombie", "Creeper and Phantom", "Skeleton", "Enderman", 1);
        add("What do you use to heal an Iron Golem?", "Gold Ingot", "Iron Ingot", "Poppy", "Repair Kit", 1);
        add("Which enchantment allows you to walk on water by turning it into ice?", "Depth Strider", "Frost Walker", "Ice Walker", "Water Walker", 1);
        add("What is the name of the alternate dimension reached via a Stronghold?", "The Nether", "The End", "The Void", "The Aether", 1);
        add("What happens to a Mooshroom when it is struck by lightning?", "It dies", "Turns into a Brown Mooshroom", "It explodes", "Nothing", 1);
        add("How many obsidian blocks are needed for the smallest possible Nether portal?", "8", "10", "12", "14", 1);
        add("Which mob can pick up and carry blocks?", "Zombie", "Enderman", "Creeper", "Villager", 1);
        add("What do you get when you smelt sand?", "Stone", "Glass", "Silicon", "Brick", 1);
        add("What tool is best for mining stone?", "Shovel", "Pickaxe", "Axe", "Hoe", 1);
        add("What do you need to craft a bed?", "Wool and Planks", "Wool and Sticks", "Leather and Planks", "Cotton and Wood", 0);
        add("Which mob explodes and is green?", "Slime", "Creeper", "Zombie", "Spider", 1);
        add("What do you use to tame a parrot?", "Bread", "Seeds", "Apples", "Cookies", 1);
        add("What is the maximum level of enchantment for a Sharpness book?", "III", "V", "IV", "X", 1);
        add("Which mob shoots arrows?", "Zombie", "Skeleton", "Creeper", "Spider", 1);
        add("What do you get from mining coal ore?", "Diamond", "Coal", "Charcoal", "Iron", 1);
        add("What is the name of the material used to upgrade diamond gear?", "Steel", "Netherite", "Obsidian", "Gold", 1);
        add("What block can be used to bounce high?", "Honey Block", "Slime Block", "Wool", "Bed", 1);
        add("Which mob is found in Ancient Cities?", "Ender Dragon", "Warden", "Wither", "Herobrine", 1);
        add("What do you use to craft a Torch?", "Stick and Coal", "Stick and Flint", "Stick and Iron", "Stick and Torch", 0);
        add("Which mob can swim in lava?", "Piglin", "Strider", "Blaze", "Ghast", 1);
        add("What is the name of the block that allows you to set your spawn point in the Nether?", "Bed", "Respawn Anchor", "Spawn Stone", "Portal", 1);
        add("What do you use to craft a Shield?", "Iron and Wood", "6 Planks and 1 Iron Ingot", "Leather and Iron", "Gold and Wood", 1);
        add("Which mob is afraid of Soul Fire?", "Zombie", "Piglin", "Enderman", "Skeleton", 1);
        add("What do you get when you kill a Shulker?", "Shulker Box", "Shulker Shell", "End Stone", "Ender Pearl", 1);
        add("How many dyes are there in Minecraft?", "12", "16", "20", "8", 1);
        add("What item is used to fly with Elytra?", "Feather", "Firework Rocket", "Gunpowder", "Paper", 1);
        add("Which mob is known for being a villager but evil?", "Witch", "Illager", "Zombie Villager", "Piglin", 1);
        add("What is the name of the structure where the Wither Skeleton spawns?", "Stronghold", "Nether Fortress", "Bastion", "End City", 1);
        add("What do you use to craft a Compass?", "Iron and Redstone", "Gold and Redstone", "Iron and Lapis", "Copper and Redstone", 0);
        add("Which mob can transform into a Witch when struck by lightning?", "Pig", "Villager", "Zombie", "Creeper", 1);
        add("What do you use to craft a Boat?", "3 Planks", "5 Planks", "7 Planks", "1 Log", 1);
        add("What is the name of the block that looks like a face and can shoot items?", "Observer", "Dispenser", "Dropper", "Hopper", 1);
        add("Which mob is the mascot of Minecraft?", "Zombie", "Creeper", "Steve", "Enderman", 1);
        add("What do you use to craft a Lead?", "String and Slimeball", "String and Leather", "Leather and Iron", "String and Wool", 0);
        add("Which mob drops Ghast Tears?", "Creeper", "Ghast", "Wither", "Phantom", 1);
        add("What is the name of the enchantment that keeps an item from being removed from armor slots?", "Curse of Vanishing", "Curse of Binding", "Unbreaking", "Mending", 1);
        add("What do you use to craft a Piston?", "Wood, Stone, Iron, Redstone", "Wood and Iron", "Stone and Redstone", "Gold and Stone", 0);
        add("Which mob is tall, black, and hates being looked at?", "Enderman", "Warden", "Slenderman", "Ghast", 0);
        add("What do you use to craft a Fence?", "Planks and Sticks", "Logs and Sticks", "Planks and Iron", "Stone and Sticks", 0);
        add("Which mob spawns in the dark and burns in sunlight?", "Creeper", "Zombie", "Spider", "Enderman", 1);
        add("What do you use to craft a Ladder?", "Planks", "Sticks", "Bamboo", "String", 1);
        add("Which mob is a neutral mob that lives in the ocean and has a long nose?", "Shark", "Dolphin", "Whale", "Squid", 1);
        add("What is the name of the block that grows in the Nether and is used for potions?", "Nether Quartz", "Nether Wart", "Soul Sand", "Glowstone", 1);
        add("What do you use to craft a Fishing Rod?", "Sticks and String", "Sticks and Iron", "Bamboo and String", "Sticks and Leather", 0);
        add("Which mob is a small, hostile insect found in Strongholds?", "Bee", "Silverfish", "Endermite", "Spider", 1);
        add("What do you use to craft a Bow?", "Sticks and String", "Bamboo and String", "Sticks and Leather", "Sticks and Iron", 0);
        add("Which mob is a neutral mob that can be sheared for wool?", "Cow", "Sheep", "Pig", "Llama", 1);
        add("What is the name of the block that is used to craft potions?", "Enchantment Table", "Brewing Stand", "Cauldron", "Furnace", 1);
        add("What do you use to craft a Cake?", "Milk, Sugar, Egg, Wheat", "Milk, Cocoa, Egg, Wheat", "Water, Sugar, Egg, Wheat", "Milk, Apple, Egg, Wheat", 0);
        add("Which mob is a hostile mob that lives in the Nether and shoots fireballs?", "Blaze", "Ghast", "Magma Cube", "Piglin", 1);
        add("What do you use to craft a Clock?", "Iron and Redstone", "Gold and Redstone", "Copper and Redstone", "Diamond and Redstone", 1);
        add("Which mob is a neutral mob that lives in the desert and has a hump?", "Donkey", "Camel", "Horse", "Llama", 1);
        add("What is the name of the block that is used to smelt ores?", "Crafting Table", "Furnace", "Anvil", "Loom", 1);
        add("What do you use to craft a Map?", "Paper and Compass", "Paper and Leather", "Paper and Glass", "Paper and Ink", 0);
        add("Which mob is a hostile mob that spawns in the ocean and shoots lasers?", "Drowned", "Guardian", "Squid", "Elder Guardian", 1);
        add("What do you use to craft a Sign?", "Planks and Stick", "Log and Stick", "Planks and String", "Paper and Stick", 0);
        add("Which mob is a neutral mob that lives in the jungle and can mimic sounds?", "Monkey", "Parrot", "Ocelot", "Panda", 1);
        add("What is the name of the block that is used to craft items?", "Furnace", "Crafting Table", "Anvil", "Chest", 1);
        add("What do you use to craft an Anvil?", "Iron Blocks and Ingots", "Steel Blocks and Ingots", "Stone Blocks and Ingots", "Obsidian and Iron", 0);
        add("Which mob is a hostile mob that spawns in the End and has wings?", "Phantom", "Ender Dragon", "Bat", "Vex", 1);
        add("What do you use to craft a Hopper?", "Iron and Chest", "Gold and Chest", "Iron and Barrel", "Wood and Iron", 0);
        add("Which mob is a neutral mob that lives in villages and can trade?", "Witch", "Villager", "Illager", "Wandering Trader", 1);
        add("Which mob has a 'charged' version when struck by lightning?", "Zombie", "Creeper", "Skeleton", "Enderman", 1);
        add("What is the name of the villager that cannot trade and wears green?", "Cleric", "Farmer", "Nitwit", "Fletcher", 2);
        add("What item is used to redirect a lightning strike?", "Iron Rod", "Lightning Rod", "Copper Rod", "Golden Rod", 1);
        add("Which mob is afraid of the Wolf?", "Zombie", "Skeleton", "Creeper", "Spider", 1);
        add("What item can you get from a Sniffer after it digs?", "Torchflower Seeds", "Carrot Seeds", "Beetroot Seeds", "Melon Seeds", 0);
        add("Which mob spawns when a player breaks an Infested Block?", "Endermite", "Silverfish", "Spider", "Slime", 1);
        add("What is the name of the effect that makes you mine slower?", "Mining Fatigue", "Haste", "Slowness", "Weakness", 0);
        add("Which mob can you milk with a bowl to get Mushroom Stew?", "Mooshroom", "Brown Mooshroom", "Both Mooshrooms", "None", 2);
        add("What is the name of the sound file used for the Cave Sounds?", "Ambient sounds", "Cave noises", "Ghost sounds", "Eerie music", 0);
        add("Which mob was the first to be added to Minecraft?", "Zombie", "Human", "Creeper", "Skeleton", 1);
        add("What is the blast power of a standard TNT block?", "2", "3", "4", "5", 2);
        add("Which block can you land on from a high place without taking any damage?", "Wool", "Bed", "Water", "Dirt", 2);
        add("How many legs does a Spider have?", "4", "6", "8", "10", 2);
        add("Which item is used to repair an Elytra?", "Phantom Membrane", "Leather", "Netherite Ingot", "String", 0);
        add("Which block is used to create a Conduit?", "Prismarine", "Sea Lantern", "Stone Bricks", "Obsidian", 0);
        add("What is the maximum stack size for most blocks?", "16", "32", "64", "100", 2);
        add("Which mob drops a Totem of Undying?", "Evoker", "Vindicator", "Witch", "Pillager", 0);
        add("What happens when a Skeleton is killed by a Charged Creeper?", "It explodes", "It drops its head", "It turns into a Wither Skeleton", "Nothing", 1);
        add("Which block can transmit redstone signals through it?", "Glass", "Slab", "Solid block", "Leaves", 2);
        add("What item is used to breed Sniffers?", "Torchflower Seeds", "Cactus", "Wheat", "Grass", 0);
        add("Which Illager carries a banner in a patrol?", "Pillager Captain", "Evoker", "Ravager", "Vindicator", 0);
        add("Which block is used to craft a Recovery Compass?", "Echo Shard", "Amethyst Shard", "Quartz", "Diamond", 0);
        add("What is the name of the enchantment that allows you to breathe underwater?", "Aqua Affinity", "Respiration", "Water Breathing", "Depth Strider", 1);
        add("Which mob is attracted to the light of a Lantern?", "None", "Zombie", "Spider", "Moth", 0);
        add("What is the name of the block that allows you to copy and paste structures?", "Command Block", "Structure Block", "Jigsaw Block", "Barrier", 1);
        add("Which mob can you feed a Golden Apple to in order to cure it?", "Zombie", "Zombie Villager", "Husk", "Drowned", 1);
        add("What is the name of the advancement for entering the Nether?", "Into the Fire", "We Need to Go Deeper", "Hot Tourist Destination", "The Netherland", 1);
        add("Which block is used to reduce the sound of footsteps and vibrations?", "Wool", "Carpet", "Sand", "Snow", 0);
        add("What is the name of the mob that looks like a small blue ghost and can hold items?", "Vex", "Allay", "Ghast", "Phantom", 1);
        add("Which item is used to trim armor?", "Smithing Template", "Diamond", "Gold Ingot", "Netherite", 0);
        add("What is the material used to craft a Netherite Ingot?", "Netherite Scrap and Gold Ingots", "Ancient Debris and Diamonds", "Obsidian and Gold", "Netherite Scrap and Diamonds", 0);
        add("Which mob is found in a Woodland Mansion?", "Evoker and Vindicator", "Witch and Skeleton", "Zombie and Creeper", "Piglin and Hoglin", 0);
        add("How many hearts does the Ender Dragon have?", "50", "100", "200", "300", 2);
        add("What is the name of the enchantment that allows you to mine faster?", "Efficiency", "Unbreaking", "Fortune", "Haste", 0);
        add("Which block is used to craft a Soul Campfire?", "Soul Sand or Soul Soil", "Netherrack", "Coal Block", "Magma Block", 0);
        add("What do you get when you use a bucket on a Cow?", "Water", "Milk", "Beef", "Leather", 1);
        add("What is the name of the block that allows redstone current to only flow in one direction?", "Redstone Wire", "Repeater", "Comparator", "Observer", 1);
        add("What is the name of the biome where many flowers are found?", "Flower Plains", "Flower Forest", "Flower Mountain", "Flower River", 1);
        add("How many iron ingots are needed to craft one iron block?", "4", "9", "16", "25", 1);
        add("Which mob drops Blaze Rods?", "Magma Cube", "Ghast", "Blaze", "Wither Skeleton", 2);
        add("What is the name of the block used to set a waypoint for a map?", "Beacon", "Banner", "Compass", "Glowstone", 1);
        add("Which item is used to craft a Potion of Swiftness?", "Sugar", "Rabbit's Foot", "Glistening Melon", "Blaze Powder", 0);
        add("What happens when you use a Shear on a Sheep?", "It dies", "It drops wool", "It turns into a Pig", "Nothing", 1);
        add("Which mob is neutral until looked at?", "Enderman", "Zombie", "Spider", "Creeper", 0);
        add("How many durability points does an Elytra have?", "232", "432", "532", "632", 1);
        add("Which block is found in the End and is white?", "End Stone", "Quartz", "Bone Block", "Obsidian", 0);
        add("How many diamonds are needed for a full set of armor?", "20", "24", "28", "32", 1);
        add("Which mob can teleport and is afraid of water?", "Enderman", "Ghast", "Shulker", "Vex", 0);
        add("What is the name of the potion that makes you invisible?", "Potion of Weakness", "Potion of Invisibility", "Potion of Harming", "Potion of Poison", 1);
        add("Which block can be used to grow Nether Wart?", "Soul Sand", "Dirt", "Netherrack", "End Stone", 0);
        add("How many gold ingots are needed to craft a Golden Apple?", "4", "8", "9", "1", 1);
        add("Which mob is found in an Ocean Monument?", "Guardian", "Elder Guardian", "Drowned", "Both Guardian and Elder Guardian", 3);
        add("What is the name of the block used to smelt ores faster than a furnace?", "Smoker", "Blast Furnace", "Brewing Stand", "Campfire", 1);
        add("Which enchantment allows you to see better underwater?", "Aqua Affinity", "Respiration", "Depth Strider", "Lure", 1);
        add("How many obsidian blocks are needed to craft an Enchantment Table?", "2", "4", "10", "14", 1);
        add("Which mob drops a Nether Star?", "Ender Dragon", "Wither", "Warden", "Iron Golem", 1);
        add("What is the name of the enchantment that prevents items from being lost on death?", "None (Gamerule keepInventory)", "Curse of Binding", "Soul Speed", "Mending", 0);
        add("Which block can be used to craft a Campfire?", "Log, Sticks, and Coal", "Stone, Sticks, and Coal", "Planks, Sticks, and Coal", "Sticks and Coal only", 0);
        add("How many eyes of ender are needed to fill a portal frame?", "8", "10", "12", "16", 2);
        add("What is the maximum distance a Redstone signal can travel without a repeater?", "10 blocks", "15 blocks", "20 blocks", "25 blocks", 1);
        add("What is the name of the biome where Bamboo grows?", "Jungle", "Bamboo Jungle", "Forest", "Savanna", 1);
        add("How many iron ingots are needed to craft a Cauldron?", "5", "7", "9", "12", 1);
        add("How many items can a single bucket of lava smelt?", "64", "100", "50", "200", 1);
        add("Which mob can drop a Rabbit's Foot?", "Rabbit", "Wolf", "Fox", "Cat", 0);
        add("What is the name of the block used to make a Map?", "Crafting Table", "Cartography Table", "Loom", "Fletcher Table", 1);
        add("Which item is used to dye a Sheep?", "Dye", "Flower", "Lapis Lazuli", "All of the above", 0);
        add("How many hits does it take to kill a Chicken with a bare hand?", "1", "2", "3", "4", 1);
        add("Which mob is known for stealing blocks?", "Enderman", "Zombie", "Villager", "Piglin", 0);
        add("What is the name of the structure where the Piglins live?", "Nether Fortress", "Bastion Remnant", "Stronghold", "Village", 1);
        add("Which item is used to craft a Shield?", "Wood and Iron", "Wood and Gold", "Stone and Iron", "Leather and Wood", 0);
        add("How many iron blocks are needed to build an Iron Golem?", "2", "4", "6", "9", 1);
        add("Which mob is the smallest in the game?", "Silverfish", "Endermite", "Baby Turtle", "Bee", 2);
        add("What is the name of the block used to make glass?", "Sand", "Gravel", "Stone", "Dirt", 0);
        add("Which item is used to craft a Bed?", "3 Wool and 3 Planks", "3 Wool and 3 Sticks", "2 Wool and 2 Planks", "1 Wool and 1 Plank", 0);
        add("How many levels are needed for a level 3 enchantment?", "10", "20", "30", "40", 2);
        add("Which mob can be found in a Desert Temple?", "None", "Zombie", "Husk", "Mummy", 0);
        add("What is the name of the item used to brew potions?", "Cauldron", "Brewing Stand", "Glass Bottle", "Nether Wart", 1);
        add("Which block can be used to craft a Piston?", "Wood, Cobblestone, Iron, Redstone", "Stone and Iron", "Wood and Redstone", "Iron and Redstone", 0);
        add("How many items are in a full stack of snowballs?", "16", "32", "64", "1", 0);
        add("Which mob is afraid of the Phantom?", "None (Players are afraid of Phantoms)", "Cat", "Creeper", "Zombie", 1);
        add("What is the name of the enchantment that increases the damage to undead mobs?", "Sharpness", "Smite", "Bane of Arthropods", "Knockback", 1);
        add("Which block is found in the Nether and is yellow?", "Glowstone", "Gold Ore", "Quartz", "Netherrack", 0);
        add("How many blocks does a Beacon affect at max level?", "20", "30", "50", "92", 3);
        add("Which mob can drop a Music Disc when killed by a Skeleton?", "Zombie", "Creeper", "Enderman", "Spider", 1);
        add("What is the name of the item used to repair an Anvil?", "Iron Ingot", "Iron Block", "None (Anvils cannot be repaired)", "Hammer", 2);
        add("Which item is used to craft an Item Frame?", "Leather and Sticks", "Paper and Sticks", "Wool and Sticks", "Leather and Iron", 0);
        add("How many hearts does the Wither have on Bedrock Edition?", "150", "300", "600", "100", 2);
        add("Which mob can be found in the End Cities?", "Enderman", "Shulker", "Ghast", "Phantom", 1);
        add("What is the name of the effect given by eating a Chorus Fruit?", "Teleportation", "Levitation", "Invisibility", "Hunger", 0);
        add("Which block is used to craft a Lantern?", "Iron Ingots and Torch", "Iron Nuggets and Torch", "Gold Nuggets and Torch", "Glass and Torch", 1);
        add("How many wood planks can be crafted from 1 log?", "2", "4", "6", "8", 1);
        add("Which mob can be used to find treasure in the ocean?", "Dolphin", "Turtle", "Squid", "Cod", 0);
        add("What is the name of the item used to spawn the Wither?", "Wither Skull and Soul Sand", "Wither Skull and Netherrack", "Skeleton Skull and Soul Sand", "Ender Pearl and Soul Sand", 0);
        add("Which block can be used to craft a Scaffolding?", "Bamboo and String", "Sticks and String", "Wood and String", "Bamboo and Leather", 0);
        add("How many different types of villager professions are there?", "10", "12", "13", "15", 2);
        add("Which mob can drop a Ghast Tear?", "Ghast", "Blaze", "Magma Cube", "Strider", 0);
        add("What is the name of the enchantment that increases the items dropped from blocks?", "Looting", "Fortune", "Efficiency", "Unbreaking", 1);
        add("Which block is used to craft a Composter?", "Wood Slabs", "Wood Planks", "Sticks", "Dirt", 0);
        add("How many levels of the Haste effect can you get from a Beacon?", "1", "2", "3", "4", 1);
        add("Which mob can be sheared to get mushrooms?", "Mooshroom", "Pig", "Cow", "Sheep", 0);
        add("What is the name of the item used to craft a Spyglass?", "Amethyst Shard and Copper", "Amethyst Shard and Gold", "Diamond and Copper", "Quartz and Copper", 0);
        add("Which block can be used to craft a Grindstone?", "Stone Slabs, Sticks, and Planks", "Stone, Sticks, and Planks", "Iron, Sticks, and Planks", "Stone Slabs and Sticks only", 0);
        add("How many hearts does a Ravager have?", "50", "100", "20", "30", 1);
        add("Which mob can be used to ride across lava in the Nether?", "Strider", "Piglin", "Hoglin", "Ghast", 0);
        add("What is the name of the enchantment that returns damage to the attacker?", "Sharpness", "Thorns", "Knockback", "Protection", 1);
        add("Which block is used to craft a Lectern?", "Wood Slabs and Bookshelf", "Wood Planks and Bookshelf", "Sticks and Bookshelf", "Wood Slabs and Books", 0);
        add("How many items does a Large Chest hold?", "27", "54", "64", "100", 1);
        add("Which mob is known for being a 'distorted' version of a player?", "Zombie", "Enderman", "Creeper", "Herobrine", 1);
        add("What is the name of the item used to craft a Pumpkin Pie?", "Pumpkin, Sugar, and Egg", "Pumpkin, Sugar, and Wheat", "Pumpkin, Egg, and Wheat", "Pumpkin and Sugar only", 0);
        add("Which block can be used to craft a Honey Block?", "4 Honey Bottles", "9 Honey Bottles", "4 Honeycomb", "9 Honeycomb", 0);
        add("How many hits can a wooden pickaxe take before breaking?", "50", "60", "32", "100", 1);
        add("Which mob can drop a Slimeball?", "Slime", "Panda", "Both Slime and Panda", "None", 2);
        add("What is the name of the enchantment that increases the damage to arthropods?", "Sharpness", "Smite", "Bane of Arthropods", "Fire Aspect", 2);
        add("Which block is used to craft a Target?", "Hay Bale and Redstone", "Wheat and Redstone", "Wool and Redstone", "Target Block and Redstone", 0);
        add("How many obsidian blocks are in the 'pillars' of the End?", "Varies", "10", "12", "14", 0);
        add("Which mob can drop a Phantom Membrane?", "Phantom", "Bat", "Vex", "Ghast", 0);
        add("What is the name of the item used to craft a Glistering Melon Slice?", "Melon Slice and Gold Nuggets", "Melon Slice and Gold Ingot", "Melon Slice and Gold Block", "Melon Slice and Glowstone", 0);
        add("Which block can be used to craft a Stonecutter?", "Stone and Iron Ingot", "Cobblestone and Iron Ingot", "Stone Slabs and Iron Ingot", "Smooth Stone and Iron Ingot", 0);
        add("How many blocks does a piece of Scaffolding go horizontally before falling?", "4", "6", "8", "10", 1);
        add("Which mob is found in a Bastion Remnant?", "Piglin Brute", "Piglin", "Hoglin", "All of the above", 3);
        add("What is the name of the mob that spawns in the Nether and looks like a floating cube of magma?", "Blaze", "Magma Cube", "Ghast", "Piglin", 1);
        add("Which block is used to craft a Barrel?", "Wood Planks and Slabs", "Wood Planks and Sticks", "Wood Logs and Slabs", "Wood Planks and Iron", 0);
        add("How many hearts does an Iron Golem have?", "50", "100", "150", "200", 1);
        add("Which mob can drop a Nautilus Shell?", "Drowned", "Fishing", "Wandering Trader", "All of the above", 3);
        add("What is the name of the enchantment that allows you to hit multiple mobs at once?", "Sharpness", "Sweeping Edge", "Knockback", "Fire Aspect", 1);
        add("Which block can be used to craft a Smithing Table?", "Wood Planks and Iron Ingots", "Wood Planks and Flint", "Wood Logs and Iron Ingots", "Wood Slabs and Iron Ingots", 0);
        add("How many different colors of beds are there?", "8", "12", "16", "20", 2);
        add("Which item is used to craft a Rabbit Stew?", "Cooked Rabbit, Mushroom, Potato, Carrot, Bowl", "Raw Rabbit, Mushroom, Potato, Carrot, Bowl", "Cooked Rabbit, Apple, Potato, Carrot, Bowl", "Cooked Rabbit, Mushroom, Bread, Carrot, Bowl", 0);
        add("What is the name of the item used to craft a Firework Rocket?", "Gunpowder and Paper", "Gunpowder and String", "Firework Star and Paper", "Both Gunpowder and Paper AND Firework Star and Paper", 3);
        add("Which block can be used to craft a Bell?", "Gold Ingots, Sticks, and Stone", "Gold Ingots and Sticks only", "Iron Ingots, Sticks, and Stone", "None (Cannot be crafted)", 3);
        add("How many items can a Furnace hold in its output slot?", "16", "32", "64", "100", 2);
        add("Which mob can be found in the Deep Dark?", "Warden", "Skeleton", "Zombie", "Creeper", 0);
        add("What is the name of the enchantment that increases the chance of catching treasure?", "Lure", "Luck of the Sea", "Fortune", "Looting", 1);
        add("Which block can be used to craft a Loom?", "Wood Planks and String", "Wood Logs and String", "Wood Planks and Sticks", "Wood Slabs and String", 0);
        add("How many items can a Hopper hold?", "1 stack", "3 stacks", "5 stacks", "9 stacks", 2);
        add("Which mob can drop an Iron Ingot?", "Zombie", "Iron Golem", "Both Zombie and Iron Golem", "None", 2);
        add("What is the name of the enchantment that makes items unbreakable?", "None (Unbreaking only increases durability)", "Mending", "Efficiency", "Fortune", 0);
        add("Which block can be used to craft a Blast Furnace?", "Furnace, Smooth Stone, and Iron Ingots", "Furnace, Stone, and Iron Ingots", "Furnace, Smooth Stone, and Gold Ingots", "Furnace, Cobblestone, and Iron Ingots", 0);
        add("How many hearts does the Warden have?", "100", "250", "500", "50", 2);
        add("Which mob can be bred with Crimson Fungus?", "Hoglin", "Piglin", "Strider", "Zoglin", 0);
        add("What is the name of the advancement for reaching the end of a world?", "The End?", "The End.", "End Game", "Victory!", 1);
        add("Which block can be used to craft a Smoker?", "Furnace and Logs", "Furnace and Planks", "Furnace and Sticks", "Furnace and Coal", 0);
        add("How many items are needed to craft an Eye of Ender?", "Ender Pearl and Blaze Powder", "Ender Pearl and Blaze Rod", "Ender Pearl and Ghast Tear", "Ender Pearl and Magma Cream", 0);
        add("Which mob can drop a Scute?", "Turtle", "Baby Turtle", "Both", "None", 1);
        add("What is the name of the enchantment that increases the knockback of a bow?", "Knockback", "Punch", "Power", "Flame", 1);
        add("Which block can be used to craft a Fletcher Table?", "Wood Planks and Flint", "Wood Logs and Flint", "Wood Planks and Sticks", "Wood Slabs and Flint", 0);
        add("How many hearts does a Horse have?", "10", "15", "Varies", "20", 2);
        add("Which mob can drop a Prismarine Shard?", "Guardian", "Drowned", "Squid", "Cod", 0);
        add("What is the name of the enchantment that makes arrows deal more damage?", "Punch", "Power", "Flame", "Infinity", 1);
        add("Which block can be used to craft a Cartography Table?", "Wood Planks and Paper", "Wood Logs and Paper", "Wood Planks and Compass", "Wood Slabs and Paper", 0);
        add("How many items are in a full stack of ender pearls?", "16", "32", "64", "1", 0);
        add("Which mob can be found in a Swamp?", "Slime", "Witch", "Frog", "All of the above", 3);
        add("What is the name of the enchantment that allows a bow to shoot infinite arrows?", "Infinity", "Power", "Flame", "Punch", 0);
        add("Which block can be used to craft a Soul Lantern?", "Iron Nuggets and Soul Torch", "Iron Ingots and Soul Torch", "Gold Nuggets and Soul Torch", "Glass and Soul Torch", 0);
        add("How many hearts does a Wolf have when tamed?", "10", "20", "30", "40", 1);
        add("Which mob can drop an Ink Sac?", "Squid", "Glow Squid", "Both", "None", 2);
        add("What is the maximum number of items a Shulker Box can hold?", "16", "27", "32", "64", 1);
        add("Which block can be used to craft a Soul Torch?", "Stick, Charcoal, and Soul Sand/Soil", "Stick and Soul Sand only", "Stick, Coal, and Soul Sand/Soil", "Both Stick, Charcoal, and Soul Sand/Soil AND Stick, Coal, and Soul Sand/Soil", 3);
        add("How many blocks high is a standard Iron Golem?", "2", "2.7", "3", "3.5", 1);
        add("Which mob can be found in a Jungle?", "Ocelot", "Parrot", "Panda", "All of the above", 3);
        add("What is the name of the enchantment that allows you to move faster on Soul Sand?", "Depth Strider", "Soul Speed", "Frost Walker", "Speed I", 1);
        add("Which block can be used to craft a Jukebox?", "8 Planks and 1 Diamond", "8 Stone and 1 Diamond", "8 Iron and 1 Diamond", "8 Wood and 1 Gold", 0);
        add("How many items can a single coal smelt?", "4", "8", "12", "16", 1);
        add("Which mob can drop a Bone?", "Skeleton", "Wolf", "Fish", "Both Skeleton and Fish", 3);
        add("What is the name of the enchantment that makes you mine faster underwater?", "Respiration", "Aqua Affinity", "Depth Strider", "Efficiency", 1);
        add("Which block can be used to craft a Note Block?", "8 Planks and 1 Redstone", "8 Stone and 1 Redstone", "8 Iron and 1 Redstone", "8 Wood and 1 Gold", 0);
        add("How many blocks high is a Ghast?", "2", "3", "4", "5", 2);
        add("Which mob can drop a String?", "Spider", "Cave Spider", "Cat", "All of the above", 3);
        add("What is the name of the enchantment that sets mobs on fire?", "Fire Aspect", "Flame", "Fire Protection", "Both Fire Aspect and Flame (for swords and bows)", 3);
        add("Which block can be used to craft a Daylight Detector?", "3 Glass, 3 Quartz, 3 Wood Slabs", "3 Glass, 3 Redstone, 3 Wood Slabs", "3 Glass, 3 Quartz, 3 Stone Slabs", "3 Glass, 3 Iron, 3 Wood Slabs", 0);
        add("How many hearts does a Ghast have?", "5", "10", "15", "20", 1);
        add("Which mob can be found in a Snowy Tundra?", "Stray", "Polar Bear", "Snow Golem (if built)", "All of the above", 3);
        add("What is the name of the enchantment that reduces fall damage?", "Protection", "Feather Falling", "Blast Protection", "Projectile Protection", 1);
        add("Which block can be used to craft a Repeater?", "2 Redstone Torches, 1 Redstone, 3 Stone", "2 Redstone Torches, 1 Redstone, 3 Cobblestone", "2 Redstone Torches, 1 Iron, 3 Stone", "2 Redstone Torches, 1 Quartz, 3 Stone", 0);
        add("How many items are in a full stack of buckets?", "1", "16", "64", "32", 1);
        add("Which mob can drop a Leather?", "Cow", "Horse", "Rabbit", "Both Cow and Horse", 3);
        add("What is the name of the enchantment that increases the damage of a crossbow?", "Power", "Piercing", "Quick Charge", "Multishot", 1);
        add("Which block can be used to craft a Comparator?", "3 Redstone Torches, 1 Quartz, 3 Stone", "3 Redstone Torches, 1 Redstone, 3 Stone", "3 Redstone Torches, 1 Iron, 3 Stone", "3 Redstone Torches, 1 Quartz, 3 Cobblestone", 0);
        add("How many hearts does a Shulker have?", "10", "15", "20", "30", 2);
        add("Which mob can be found in a Savanna?", "Llama", "Horse", "Donkey", "All of the above", 3);
        add("What is the name of the enchantment that makes a crossbow load faster?", "Power", "Quick Charge", "Piercing", "Multishot", 1);
        add("Which block can be used to craft an Observer?", "2 Redstone, 1 Quartz, 6 Cobblestone", "2 Redstone, 1 Quartz, 6 Stone", "2 Redstone, 1 Diamond, 6 Cobblestone", "2 Redstone, 1 Quartz, 6 Iron", 0);
        add("How many hearts does an Endermite have?", "4", "8", "10", "12", 1);
        add("Which mob can be found in a Mega Taiga?", "Wolf", "Fox", "Bear", "Both Wolf and Fox", 3);
        add("What is the name of the enchantment that allows a crossbow to shoot 3 arrows at once?", "Multishot", "Piercing", "Quick Charge", "Power", 0);
        add("Which block can be used to craft a Dispenser?", "7 Cobblestone, 1 Bow, 1 Redstone", "7 Cobblestone, 1 Dropper, 1 Redstone", "7 Stone, 1 Bow, 1 Redstone", "7 Cobblestone, 1 Bow, 1 String", 0);
        add("How many hearts does a Silverfish have?", "4", "8", "10", "12", 1);
        add("Which mob can be found in a Mushroom Forest?", "Mooshroom", "Cow", "Sheep", "Pig", 0);
        add("What is the name of the enchantment that allows a tool to mine blocks exactly as they are?", "Fortune", "Silk Touch", "Efficiency", "Unbreaking", 1);
        add("Which block can be used to craft a Dropper?", "7 Cobblestone and 1 Redstone", "7 Stone and 1 Redstone", "7 Cobblestone and 1 Bow", "7 Cobblestone and 1 Iron", 0);
        add("How many hearts does a Blaze have?", "10", "20", "30", "40", 1);
        add("Which mob can be found in a Soul Sand Valley?", "Skeleton", "Ghast", "Enderman", "Both Skeleton and Ghast", 3);
        add("What is the name of the enchantment that increases the damage against aquatic mobs?", "Sharpness", "Impaling", "Bane of Arthropods", "Smite", 1);
        add("Which block can be used to craft a Lever?", "1 Stick and 1 Cobblestone", "1 Stick and 1 Stone", "1 Stick and 1 Iron", "1 Stick and 1 Redstone", 0);
        add("How many items can a single blaze rod smelt?", "8", "12", "16", "20", 1);
        add("Which mob can drop a Magma Cream?", "Magma Cube", "Slime", "Blaze", "Ghast", 0);
        add("What is the name of the enchantment that allows a trident to return to the player?", "Loyalty", "Riptide", "Channeling", "Impaling", 0);
        add("Which block can be used to craft a Tripwire Hook?", "1 Iron, 1 Stick, 1 Plank", "1 Iron, 1 String, 1 Plank", "1 Iron, 1 Stick, 1 Stone", "1 Gold, 1 Stick, 1 Plank", 0);
        add("How many hearts does a Magma Cube have?", "Varies by size", "10", "20", "30", 0);
        add("Which mob can drop a Netherite Scrap?", "None", "Piglin", "Hoglin", "Warden", 0);
        add("What is the blast resistance of a Dragon Egg?", "9", "12", "15", "20", 0);
        add("How many ticks are in a standard Minecraft game day (20 minutes)?", "12000", "24000", "36000", "48000", 1);
        add("What is the exact percentage chance of a Pink Sheep spawning naturally?", "0.164%", "0.5%", "1%", "0.05%", 0);
        add("In Java Edition, how much health does a small Slime (size 1) have?", "1 heart", "2 hearts", "4 hearts", "0.5 hearts", 0);
        add("What is the maximum number of entities that can cram into a single block by default?", "16", "24", "32", "64", 1);
        add("How many items can a single block of coal smelt in a furnace?", "64", "80", "100", "120", 1);
        add("What is the maximum horizontal distance a Sculk Sensor can detect vibrations?", "4 blocks", "8 blocks", "12 blocks", "16 blocks", 1);
        add("How many vibrations must a player trigger to spawn a Warden?", "2", "3", "4", "5", 2);
        add("What is the hardness value of an Obsidian block?", "10", "50", "100", "1200", 1);
        add("Which mob has the highest base health in the game?", "Ender Dragon", "Wither", "Warden", "Giant", 2);
        add("What is the base damage of a Warden's sonic boom attack?", "10", "15", "20", "25", 1);
        add("What is the exact speed of a Boat on Blue Ice in blocks per second?", "20", "40.3", "72.7", "100.1", 2);
        add("What is the blast resistance of Bedrock?", "1,000,000", "3,600,000", "12,000", "Unlimited", 1);
        add("How many durability points does a Netherite Chestplate have?", "492", "592", "692", "792", 1);
        add("What is the name of the advancement for having every potion effect applied at once?", "A Furious Cocktail", "How Did We Get Here?", "The End Again", "Overkill", 1);
        add("How many different types of tropical fish can exist in Minecraft?", "1000", "2700", "3584", "5000", 2);
        add("In what version was the 'Sprinting' mechanic officially introduced?", "Beta 1.7", "Beta 1.8", "1.0", "1.2", 1);
        add("What was the first block ever added to Minecraft during its development?", "Stone", "Dirt", "Grass", "Cobblestone", 2);
        add("What is the maximum level for the 'Luck of the Sea' enchantment?", "II", "III", "IV", "V", 1);
        add("How many hearts of health does a Sniffer have?", "7", "10", "14", "20", 2);
        add("What is the blast power of an End Crystal?", "4", "5", "6", "7", 2);
        add("How many durability points does a Golden Pickaxe have?", "32", "64", "128", "256", 0);
        add("What is the specific chance of a spider spawning with a status effect on Hard?", "5%", "10%", "15%", "20%", 1);
        add("How many hearts of health does a Giant have?", "10", "50", "100", "200", 2);
        add("What is the internal ID for the 'Illusioner' mob?", "illusioner", "illager_illusion", "hidden_illager", "phantom_illager", 0);
        add("How many ticks of invulnerability does a player get after taking damage?", "5", "10", "20", "40", 1);
        add("How many blocks away can a Bee travel from its hive before it gets lost?", "10", "22", "50", "100", 1);
        add("What is the name of the advancement for visiting every biome?", "World Traveler", "Adventuring Time", "Land of Wonders", "Explorer", 1);
        add("How many durability points does a Diamond Pickaxe have?", "1031", "1561", "2031", "2501", 1);
        add("What is the internal ID for a Zombie Horse?", "zombie_horse", "horse_zombie", "undead_horse", "dead_horse", 0);
        add("How many hunger points does a Golden Carrot restore?", "2", "4", "6", "8", 2);
        add("What is the blast power of a Charged Creeper?", "3", "4", "6", "8", 2);
        add("How many durability points does a Flint and Steel have?", "32", "64", "128", "256", 1);
        add("In which year was the first public 'Pre-Classic' version of Minecraft released?", "2008", "2009", "2010", "2011", 1);
        add("What is the name of the advancement for killing every hostile mob?", "Monster Hunter", "Monsters Hunted", "Slayer", "Exterminator", 1);
        add("How many hearts of health does a Camel have?", "16", "32", "50", "10", 0);
        add("What is the duration of the 'Darkness' effect applied by a Sculk Shrieker?", "5s", "10s", "12s", "15s", 2);
        add("Which mob has the internal ID 'evocation_illager' in older versions?", "Evoker", "Vindicator", "Pillager", "Illusioner", 0);
        add("How many items can a single stick smelt?", "0.5", "1", "1.5", "2", 0);
        add("What is the maximum number of trades a villager can offer per level?", "1", "2", "3", "4", 1);
        add("How many experience points are dropped by the Ender Dragon on its first death?", "1000", "5000", "10000", "12000", 3);
        add("What is the blast resistance of a block of Crying Obsidian?", "600", "1200", "100", "50", 1);
        add("How many durability points does a standard Elytra have?", "232", "432", "532", "632", 1);
        add("What is the name of the hidden splash text that appears if 'splashes.txt' is missing?", "null", "missingno", "splash_error", "minecraft", 1);
        add("How many hearts of damage does a Warden's melee attack deal on Hard?", "15", "30", "45", "60", 2);
        add("What is the range of a Warden's sonic boom attack in blocks?", "5", "10", "15", "20", 2);
        add("How many durability points does a Gold Sword have?", "32", "64", "131", "250", 0);
        add("What is the name of the advancement for trading with a villager at the world height limit?", "Star Trader", "High Roller", "Top Merchant", "Sky Trader", 0);
        add("Which status effect can a spider NOT naturally spawn with on Hard?", "Strength", "Speed", "Invisibility", "Slowness", 3);
        add("What is the hardness value of a block of Deepslate?", "3", "4.5", "6", "1.5", 0);
        add("How many items can a single block of dried kelp smelt?", "10", "20", "30", "40", 1);
        add("What is the chance of a Skeleton Horse trap spawning during a thunderstorm on Normal?", "1.5-4%", "0.75-1.5%", "3.75-10%", "5-10%", 0);
        add("How many chunks are stored in a single Minecraft Region (.mca) file?", "256", "512", "1024", "2048", 2);
        add("What is the maximum level of a Sharpness enchantment book found in a Loot Chest?", "III", "IV", "V", "II", 2);
        add("How many hearts of health does a Wither have in Minecraft: Bedrock Edition?", "150", "300", "600", "1000", 2);
        add("What is the width of an Enderman's hitbox in blocks?", "0.5", "0.6", "0.7", "0.8", 1);
        add("How many blocks per second is the terminal velocity of a falling player?", "20", "50", "78.4", "100", 2);
        add("What is the name of the sound file used for a Creeper's fuse?", "fuse", "hiss", "prime", "random.fuse", 3);
        add("How many levels of the 'Haste' effect can be obtained from a full Beacon?", "I", "II", "III", "IV", 1);
        add("What is the blast resistance of a block of Netherite?", "100", "600", "1200", "1200", 2);
        add("How many items can a single Bamboo smelt?", "0.25", "0.5", "0.75", "0.1", 0);
        add("What is the name of the advancement for entering a Stronghold?", "Eye Spy", "Stronghold", "The End?", "Into the Void", 0);
        add("How many experience points are dropped by the Ender Dragon on subsequent deaths?", "100", "500", "1000", "2000", 1);
        add("What is the name of the sound that plays when an Enderman teleports?", "vloop", "whoosh", "portal", "teleport", 0);
        add("How many blocks away can a Conduit provide its effects at maximum power?", "32", "64", "96", "128", 2);
        add("What is the chance of a Zombified Piglin spawning with an enchanted Golden Sword on Hard?", "5%", "10%", "25%", "50%", 2);
        add("How many durability points does an Iron Sword have?", "131", "250", "500", "64", 1);
        add("What is the name of the music track that plays during the Minecraft credits?", "Sweden", "Wet Hands", "Alpha", "Beginning", 2);
        add("How many different languages is Minecraft officially translated into?", "Over 50", "Over 100", "Over 150", "Over 200", 1);
        add("What is the maximum level for an Efficiency enchantment book found in a chest?", "III", "IV", "V", "II", 2);
        add("How many blocks high is the build limit in Minecraft version 1.7?", "128", "256", "320", "512", 1);
        add("What is the chance of a villager turning into a Witch when struck by lightning?", "10%", "50%", "100%", "25%", 2);
        add("What is the blast power of a Wither's birth explosion?", "5", "7", "10", "12", 1);
        add("What is the name of the achievement for trading with a villager?", "What a Deal!", "Trade of a Lifetime", "Merchant", "Business", 0);
        add("How many blocks can a Boat travel on blue ice per second?", "20", "40", "72.7", "100", 2);
        add("What is the hardness of a block of Stone?", "1.5", "2", "3", "4", 0);
        add("How many experience points are needed to reach Level 30 from Level 0?", "825", "1395", "1500", "2000", 1);
        add("What is the blast power of a standard Creeper?", "2", "3", "4", "5", 1);
        add("What is the reach distance for a player in Creative mode in blocks?", "4.5", "5", "6", "7", 1);
        add("How many durability points does a Gold Axe have?", "32", "64", "131", "250", 0);
        add("In which version was the 'Experience' system first introduced?", "Beta 1.8", "Beta 1.7", "1.0", "1.2", 0);
        add("In which version was the 'Hunger' mechanic introduced?", "Beta 1.7", "Beta 1.8", "1.0", "1.2", 1);
        add("What is the chance of a spider spawning with Strength on Hard?", "1.25%", "2.5%", "5%", "10%", 0);
        add("How many hearts of health does a fully grown Slime of size 4 have?", "4", "16", "20", "32", 1);
        add("What happens when you use a Potion of Healing on a Zombie?", "It heals", "It takes damage", "It turns into a Villager", "Nothing", 1);
        add("How many blocks high can a player jump with Jump Boost II?", "1.5", "2.5", "3.5", "4.5", 1);
        add("What is the rarest biome in the game (pre-1.18)?", "Mushroom Fields", "Modified Jungle Edge", "Ice Spikes", "Eroded Badlands", 1);
        add("How many durability points does a Netherite Sword have?", "1031", "1561", "2031", "2501", 2);
        add("Which status effect makes you take 20% less damage per level?", "Strength", "Resistance", "Regeneration", "Absorption", 1);
        add("What is the name of the 'blue' wood found in the Nether?", "Warped Wood", "Crimson Wood", "Soul Wood", "Blue Wood", 0);
        add("How many ticks does a standard Redstone Repeater delay at its default setting?", "1", "2", "3", "4", 1);
        add("What is the maximum number of blocks a Beacon can extend its reach horizontally at level 4?", "50", "92", "100", "128", 0);
        add("Which material is used to craft a Smithing Template?", "Diamonds", "Gold", "Netherite", "Emeralds", 0);
        add("What is the hardness value of a block of Coal?", "3", "4", "5", "0.5", 0);
        add("What is the blast resistance of a block of Dirt?", "0.5", "1", "2", "3", 0);
        add("What is the hardness of a block of Bedrock?", "1000", "0", "-1", "Infinite", 2);
        add("What is the name of the sound track that plays in the Main Menu?", "Sweden", "Haggstrom", "Minecraft", "All of the above", 3);
        add("What is the chance of a baby zombie spawning instead of a normal one?", "5%", "10%", "1%", "2.5%", 0);
        add("What is the blast resistance of a block of End Stone?", "9", "15", "30", "45", 0);
        add("Which mob has the ID 'minecraft:giant'?", "Iron Golem", "Giant", "Warden", "Ender Dragon", 1);
        add("What is the maximum number of items in a single Hopper slot?", "16", "32", "64", "1", 2);
        add("Which item is used to duplicate a Smithing Template?", "Netherite", "Diamond", "Gold", "Emerald", 1);
    }

    private static void add(String q, String a1, String a2, String a3, String a4, int correct) {
        POOL.add(new TriviaQuestion(q, List.of(a1, a2, a3, a4), correct));
    }

    public static TriviaQuestion getRandom() {
        return POOL.get(RANDOM.nextInt(POOL.size()));
    }
}
